# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.jwtsecret: '%env(JWT_SECRET)%'
    app.locales: [en, fr]
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind: 
            string $pdfDirectory: '%kernel.project_dir%/public/pdf'

 
 
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # Allow injecting the Users entity into controllers
    App\Entity\Users:
        public: true
    # Allow injecting Operations entity into controllers
    App\Entity\Operations:
        public: true
    # Allow injecting Invoices entity into controllers
    App\Entity\Invoices:
        public: true

    App\Twig\DisplayFirstRoleExtension:
        tags:
            - { name: twig.extension }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\UserLoginListener:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }
            
    App\EventListener\OperationStatusListener:
        arguments:
            $loggerService: '@App\Service\LoggerService'
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
    
    App\EventListener\ExceptionListener:
        arguments: ['@twig']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

            
    App\Service\LoggerService:
        arguments:
            $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'